version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: controller
    labels:
      lagoon.type: none
    networks:
      - default
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=1313
      - LAGOON_ROUTE=http://hugo.docker.amazee.io
    labels:
      lagoon.type: node
    networks:
      - amazeeio-network
      - default
    ports:
      - 1313:1313
    tty: true
    volumes:
      - ./hugo:/hugo:delegated

networks:
  amazeeio-network:
    external: true